apiVersion: apps/v1
kind: Deployment
metadata:
  name: stockjedi-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: stockjedi-backend
  template:
    metadata:
      labels:
        app: stockjedi-backend
    spec:
      containers:
      - name: backend
        image: stockjedi-backend:latest
        ports:
        - containerPort: 8000
        envFrom:
        - secretRef:
            name: stockjedi-secrets
---
apiVersion: v1
kind: Service
metadata:
  name: stockjedi-backend-svc
spec:
  selector:
    app: stockjedi-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
